" VimDebugger (PHP)
nmap <F4> :DbgListen<CR>
nmap <F5> :DbgStepInto<CR>
nmap <F6> :DbgStepOver<CR>
nmap <F7> :DbgStepOut<CR>
nmap <F8> :DbgRun<CR>
nmap <F9> :DbgDetach<CR>
" Spanish layout
nmap ñbp :DbgToggleBreakpoint<CR>
