" GVIM

if has("gui_running")

	" winpos 240 36 " Initial position on screen

	set lines=36 " Lines
	set columns=120 " Columns
	"set transparency=5 FIXME

	set guioptions-=M " System menu is not sourced
	set guioptions-=m " No menu
	set guioptions-=T " No toolbar
	set guioptions-=r " No scrollbar on the right
	set guioptions-=R " No scrollbar on the right when split
	set guioptions-=l " No scrollbar on the left
	set guioptions-=l " No scrollbar on the left when split
	set guioptions-=b " No scrollbar on the bottom
	set guioptions=ci

	" Custom themes
	colo noijd

	" TODO resolution? 96x96
	let height = str2nr(system("xdpyinfo | grep dimension | awk '{ print $2 }' | awk -Fx '{print $2}'"))

	if height < 1500
		set guifont=Monospace\ 14
	else
		set guifont=DejaVu\ Sans\ Mono\ 10
	endif

endif
