set nocompatible

" TODO Split in several files; langs?, global, edit, commands/macros?

" Para que actualice Vim al cambiar la configuración
" autocmd! BufWritePost vimrc so ~/.vim/vimrc
" autocmd! BufWritePost gvimrc so ~/.vim/gvimrc
" autocmd BufWritePost *.vim so ~/.vim/maps.vim
" autocmd BufWritePost *.vim so ~/.vim/plugins.vim

" Pathogen.vim
filetype off 
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" Vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

set shell=/bin/zsh

set noautochdir " Don't auto-change directory to current file
set autoread " Set to auto read when a file is changed from the outside

set showcmd " Show command info in the status line

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

set wildmenu " Enhace mode command line completion

set wildignore+=*.jpg,*.jpeg,*.png,*.gif " Ignore images
set wildignore+=*.pdf " Ignore PDF files
set wildignore+=*.swp " Ignore temporary files
set wildignore+=*.svn,*.git " Ignore VCS files

set foldnestmax=3

set noeol " Prevent vim from adding an empty line at the end of file

set nomodeline

set lbr " Wrap text instead of being on one line

set autoindent
" Copia el indentado
set copyindent
" figure out indent when ; is pressed TODO Funcionará bien en los for y comentarios?
"set cinkeys+=;
" Tomo como referencia shiftwidth en vez de tabstop
set smarttab
" Indentado automático de 4 espacios
set shiftwidth=4
set tabstop=4 " A tab is four spaces
set softtabstop=4
set showmatch " Show matching parenthesis
set smarttab

" Para localizar fácilmente la línea
set cursorline

" Comienza la búsqueda desde el principio del archivo
set wrapscan
" Case insensitive search
set ic
" Si hay una mayúscula la búsqueda no es insensible
set smartcase
set hls " Higlhight search
" Los caracteres '.', '*', '[' y ']' tienen un significado especial en las búsquedas
set magic
set incsearch " Show search matches as you type

" ¿Qué hace? TODO
"set laststatus=2

" Para que muestre información de líneas, columnas y porcentaje en la línea de estado TODO rulerformat
set ruler
"set rulerformat=%15(%c%)

set report=0 " Report when N lines were changed

set nu " Turn line numbering. Turn it off with 'set nonu'
"set relativenumber " Relative line numbering. Version 7.3
set scrolloff=2 " Start scrolling at this number of lines from the bottom

set splitright " Split vertically to the right

set lazyredraw " To improve macros

set history=600 " Command history size

set colorcolumn=80 " Mark column

"set isk+=_,$,@,%,#,-,?,%,& " none of these should be word dividers, so make them not be TODO Joderá algo?

" Modifica el comportamiento de TODO Comprobar comportamiento específico
set backspace=start,indent,eol

set completeopt+=menuone,preview " Autocompletion

set spell

" Directories for swp files
set backupdir=~/.vim.backup
set directory=~/.vim.backup

" Para el botón derecho
set mousemodel=extend

" Para que busque en otros sitios además de en el propio directorio
" set tags=~/.vim.private/Tags/php.tags

" Local scripts/helpfiles FIXME pathogen
"helptags $HOME/.vim/doc

" Colours
set t_Co=256

" Always enable syntax highlight
syn on

" Default theme
colo elflord

" MAPS
source ~/.vim/maps/vi-like.vim     " GVim, Vim, Vimperator...
source ~/.vim/maps/vim.vim " Only GVim and Vim
"source ~/.vim/maps/es.vim " Spanish layout
source ~/.vim/maps/us.vim  " English layout

" PLUGINS
source ~/.vim/plugins.vim
source ~/.vim/vundle.vim

" COMMANDS
source ~/.vim/commands.vim

" Configuración adicional que puede depender del entorno TODO
source ~/.dot.private/vim/Config/vimrc.vim

" Turn on again
filetype plugin indent on
